### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by VlaDerkach** [Mintbase/Grants-Program#19]
Hi! 
I've found a broken "tech stack" link in the 1st paragraph of the [📬 Suggest a Project section of README.md](https://github.com/Mintbase/Grants-Program#mailbox_with_mail-suggest-a-project).
Can you fix it please? 🙏

**Comment by microchipgnu** [comment]
Hey! Thanks for the comment. I have just changed the README.

New link is https://docs.mintbase.io/dev/getting-started/our-stack
